#!/bin/bash
# shellcheck disable=SC2046
## runs 'cargo test' and saves output to test_results.txt in root folder
require git cargo

git_branch_matches "master" "main" "devel" || return 0
is_cargo_project || return 0

git_hook_matches "pre-commit" "pre-merge-commit" "commit-msg" || return 0
git_hook_matches "pre-commit" "pre-merge-commit" && background_schedule && return 0
git_hook_matches "commit-msg" && background_wait && return $(background_result)

# Run cargo test and redirect output to test_results.txt in root directory
run_test sh -c "cd $WORKTREE_DIR && cargo test > test_results.txt 2>&1"